Update readme.en.md
Maikuolan/phpMussel pull request #180
Opened 2018-12-28 21:01 UTC by mphasize

Added a bit of information about including the `phpmussel*.db` signature files, when the engine should trigger on the test files. Also trying to explain that cache may prevent a re-scan after changing the `Active` configuration setting.

Unfortunately I can only provide a change for the English docs and not the other translations.

2018-12-28 21:02 UTC, mphasize commented
Proposing this addition to the docs after trying to find some info related to this https://github.com/phpMussel/phpMussel/issues/178

2018-12-28 21:20 UTC, DanielRuf requested changes

2018-12-28 21:20 UTC, DanielRuf commented on _docs/readme.en.md
> +*Note: Signature files must firstly be installed, before you can activate them. For the test files to trigger, you also need to include the phpmussel signature files. After changing the configuration
phpmussel => phpMussel

2018-12-28 21:21 UTC, DanielRuf commented
I do not know but can you also update the German docs?

2018-12-28 21:31 UTC, mphasize commented on _docs/readme.en.md
> +*Note: Signature files must firstly be installed, before you can activate them. For the test files to trigger, you also need to include the phpmussel signature files. After changing the configuration
Should be fixed now.

2018-12-28 21:31 UTC, mphasize commented
True, German was possible.

2018-12-28 23:06 UTC, DanielRuf requested changes

2018-12-28 23:06 UTC, DanielRuf commented on _docs/readme.de.md
> +7) Der Installationsvorgang wurde nun fertiggestellt. Sie sollten nun das Programm auf ordnungsgemäße Funktion testen. Sie sollten nun die im Paket enthaltenen Testdateien `_testfiles` auf Ihre Webse
erkann => erkannt

2018-12-30 15:23 UTC, mphasize commented on _docs/readme.de.md
> +7) Der Installationsvorgang wurde nun fertiggestellt. Sie sollten nun das Programm auf ordnungsgemäße Funktion testen. Sie sollten nun die im Paket enthaltenen Testdateien `_testfiles` auf Ihre Webse
👍

2018-12-30 15:33 UTC, DanielRuf approved these changes

2018-12-31 04:07 UTC, Maikuolan approved these changes

2018-12-31 04:11 UTC, Maikuolan commented
Good idea, adding this information to the documentation, and thanks for the PR. Changes look good; I'll merge the PR now. :+1: 😊

> Unfortunately I can only provide a change for the English docs and not the other translations.

No problem. I'll get that sorted out at some point prior to the next release.

2018-12-31 04:13 UTC, merged